language: node_js
node_js:
- "0.10"
before_install:
- openssl aes-256-cbc -K $encrypted_a7dc3a9bd345_key -iv $encrypted_a7dc3a9bd345_iv
  -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d
script:
- if [ files/amy_hemmeter_cv.pdf -ot cv.md ]; then markdown-pdf -o files/amy_hemmeter_cv.pdf -s css/cv.css -b 1in cv.md && echo "PDF UPDATED"; fi
after_success:
- git remote set-url origin git@github.com:ahemmeter/ahemmeter.github.io.git
- git checkout master
- eval `ssh-agent`
- chmod 600 .travis/deploy_key.pem
- ssh-add .travis/deploy_key.pem
- git config user.name "travis-autodeployer"
- git config user.email "wjbarlow+github-buildbot@ncsu.edu"
- git config push.default simple
- git add files/amy_hemmeter_cv.pdf
- git status -uno
- git commit -m "deploying updated CV (pdf version)"
- git log -5 --pretty=oneline
- git push
